# Mar. 23rd
#dir_path: 2022-03-24_Array_Test_Results
#file_name: F9P5_F11P5_F5P9_Beam_0324 # w/o .txt

# Mar. 24th
#dir_path: 2022-03-24_Array_Test_Results_8PM
#file_name: F9P5_F11P5_F5P9_Beam_0324_8PM # w/o .txt

# Mar. 25th
#dir_path: 2022-03-25_Array_Test_Results
#file_name: F9P5_F11P5_F5P9_Beam_0325

# Mar. 26th
# TDC test 1
#dir_path: 2022-03-26_Array_Test_Results
#file_name: F9P5_F11P5_F5P9_Beam_8pm_autoReset1_0326

# TDC test 2
#dir_path: 2022-03-26_Array_Test_Results
#file_name: F9P5_F11P5_F5P9_Beam_8pm_set_TDC_level_0326

# Default setting
#dir_path: 2022-03-26_Array_Test_Results
#file_name: F9P5_F11P5_F5P9_Beam_0326_8PM

# Mar. 27th
#dir_path: 2022-03-27_Array_Test_Results
#file_name: F9P5_F11P5_F5P9_Beam_0327

# Mar. 28th
# Beam was downed. No data

# Mar. 29th
# Change pixel of board F5 from P9 to P5
#dir_path: 2022-03-29_Array_Test_Results
#file_name: F9P5_F11P5_F5P5_Beam

# Default setting
#dir_path: 2022-03-30_Array_Test_Results
#file_name: F9P5_F11P5_F5P9_Beam_started_0329

# P5 vs P9 comparing
# 300 files for each data set
# P9
#dir_path: 2022-03-29_Array_Test_Results
#file_name: F9P5_F11P5_F5P5_Beam

# P5
#dir_path: 2022-03-29_Array_Test_Results
#file_name: F9P5_F11P5_F5P5_Beam

# Mar. 31 - P5 for all boards one more time
#dir_path: 2022-03-31_Array_Test_Results
#file_name: F9P5_F11P5_F5P5_Beam

# Apr. 01
#dir_path: 2022-04-01_Array_Test_Results
#file_name: F9P5_F11P5_F5P5_Beam

# Apr. 02
#dir_path: 2022-04-02_Array_Test_Results
#file_name: F9P5_F11P5_F5P5_Beam

# Apr. 03
#dir_path: 2022-04-03_Array_Test_Results
#file_name: F9P5_F11P5_F5P5_Beam

# Apr. 04
#dir_path: 2022-04-04_Array_Test_Results
#file_name: F9P5_F11P5_F5P5_Beam

# Apr. 05 -> B1's Cal code peak has tails
#dir_path: 2022-04-05_Array_Test_Results
#file_name: F9P5_F11P5_F5P9_Beam


# Apr. 08 (from midnight of Thurs)
#dir_path: 2022-04-08_Array_Test_Results
#file_name: F9P5_F11P5_F5P5_Beam

# Seperate by time
#file_name: am1p13_2p13
#file_name: am2p13_3p13
#file_name: am3p13_4p13
#file_name: am4p13_5p13
#file_name: am5p13_6p13
#file_name: am6p00_7p33


# Apr. 09
#dir_path: 2022-04-09_Array_Test_Results
#file_name: F9P5_F11P5_F5P5_Beam_HV235

# Seperate by time
#file_name: am1p18_2p18
#file_name: am2p18_3p18
#file_name: am3p18_4p18
#file_name: am4p18_5p18
#file_name: am5p18_6p45

# 230 V
#file_name: F9P5_F11P5_F5P5_Beam_HV230

# 225 V
#file_name: F9P5_F11P5_F5P5_Beam_HV225

# 220 V
#file_name: F9P5_F11P5_F5P5_Beam_HV220


# Apr.10
dir_path: 2022-04-10_Array_Test_Results
file_name: F9P5_F11P5_F5P5_Beam_HV215

#file_name: F9P5_F11P5_F5P5_Beam_HV210
